apiVersion: apps/v1
kind: Deployment
metadata:
 name: oauthentication-service
spec:
 replicas: 2
 selector:
   matchLabels:
     app: oauthentication-service
 template:
   metadata:
     labels:
       app: oauthentication-service
   spec:
     containers:
     - name: oauthentication-service-container
       image: sriharipriya/oauthentication_service:latest
       ports:
       - containerPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: service-a
spec:
replicas: 2
selector:
  matchLabels:
    app: service-a
template:
  metadata:
    labels:
      app: service-a
  spec:
    containers:
    - name: service-a-container
      image: sriharipriya/service_a_microservice:latest
      ports:
      - containerPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: service-b
spec:
replicas: 2
selector:
  matchLabels:
    app: service-b
template:
  metadata:
    labels:
      app: service-b
  spec:
    containers:
    - name: service-b-container
      image: sriharipriya/service_b_microservice:latest
      ports:
      - containerPort: 8085
has context menu
